### ISSUE TITLE
Create automatic pre-release for all/new Lua versions

### ISSUE THREAD

**Issue by luttje** [luttje/lua-wasm#1]
In the README I promised:

> _A GitHub action periodically checks for updated Lua versions and automatically builds (untested) [pre-releases](https://github.com/luttje/lua-wasm/releases)._

Though I have not yet implemented that. The ci.yml code addition will look something like this:
```yml
    - 
      name: Publish automatic pre-release
      uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "{{{{{{ LUA VERSION HERE }}}}}}-alpha"
        prerelease: true
        title: "{{{{{{ LUA VERSION HERE }}}}}} (automated build)"
        files: ZipContainingDist.zip
```
